# Versi Docker Compose yang digunakan
version: "3.2"

# Daftar layanan yang didefinisikan
services:
  # Layanan untuk shipping service
  shipping:
    # Gunakan image terbaru dari shipping service
    image: widiarrohman/shipping-service:latest
    # Tentukan nama container
    container_name: shipping-service
    # Map port lokal 3001 ke port 3001 di dalam container
    ports:
      - 3001:3001
    # Set variabel lingkungan AMQP_URL untuk koneksi ke RabbitMQ
    environment:
      - AMQP_URL=amqp://admin:admin@rabbitmq:5672
    # Hubungkan layanan ke jaringan yang telah didefinisikan
    networks:
      - my-network

# Definisikan jaringan yang digunakan
networks:
  my-network:
    # Gunakan driver bridge untuk jaringan
    driver: bridge
