version: "3.2"
services:
  shipping:
    image: widiarrohman/shipping-service:latest
    container_name: shipping-service
    ports:
      - 3001:3001
    environment:
      - AMQP_URL=amqp://localhost:5673
