# Versi Docker Compose yang digunakan
version: "3.2"

# Daftar layanan yang didefinisikan
services:
  # Layanan untuk RabbitMQ
  rabbitmq:
    # Gunakan image RabbitMQ versi 3.8 dengan manajemen dan Alpine sebagai base image
    image: rabbitmq:3.8-management-alpine
    # Tentukan nama container
    container_name: rabbitmq-container
    # Map port lokal 5673 ke port 5672 di dalam container untuk AMQP
    # Map port lokal 15673 ke port 15672 di dalam container untuk manajemen web
    ports:
      - "5673:5672"
      - "15673:15672"
    # Set variabel lingkungan untuk pengaturan RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    # Hubungkan layanan ke jaringan yang telah didefinisikan
    networks:
      - my-network

  # Layanan untuk order service
  order:
    # Gunakan image terbaru dari order service
    image: widiarrohman/order-service:latest
    # Tentukan nama container
    container_name: order-service
    # Map port lokal 3000 ke port 3000 di dalam container
    ports:
      - 3000:3000
    # Set variabel lingkungan AMQP_URL untuk koneksi ke RabbitMQ
    environment:
      - AMQP_URL=amqp://admin:admin@rabbitmq:5672
    # Menentukan dependensi layanan terhadap rabbitmq
    depends_on:
      - rabbitmq
    # Hubungkan layanan ke jaringan yang telah didefinisikan
    networks:
      - my-network

# Definisikan jaringan yang digunakan
networks:
  my-network:
    # Gunakan driver bridge untuk jaringan
    driver: bridge
