name: Node.js CI

on:
  push:
    branches: ["karsajobs-ui"]
  pull_request:
    branches: ["karsajobs-ui"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push App Karsajobs
        run: |
          docker build . --tag ghcr.io/caturheri/karsajobs-ui:latest
          docker push ghcr.io/caturheri/karsajobs-ui:latest
