name: Node.js CI

on:
  push:
    branches: ["karsajobs-ui"]
  pull_request:
    branches: ["karsajobs-ui"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.21]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Lint Dockerfile
        run: |
          sudo apt-get update
          sudo apt-get install -y hadolint
          hadolint -f dockerfile Dockerfile

      - name: Build App Karsajobs-UI
        run: |
          docker build -t karsajobs-ui:latest .
          docker push karsajobs-ui:latest
